### PR TITLE
Raise pubsub read timeout to stop DeadlineExceeded errors

### PR DESCRIPTION
**Pull request by mjneth**
- Raises the pubsub read timeout to make the constant DeadlineExceeded errors stop
- Adds a "Pulling new messages" log that only outputs once a minute since the DeadLineExceeded error was how I knew the process was fully started, taking messages, and not hung :P. Now we'll see this to know the process is alive:
```
2023-06-02 20:34:02 [info     ] Pulling new messages           [root] 
2023-06-02 20:35:16 [info     ] Pulling new messages           [root] 
2023-06-02 20:36:30 [info     ] Pulling new messages           [root]
```
- Removes python 3.6 from the pytest workflow since it was failing here:
https://github.com/cloudchacho/taskhawk-python/actions/runs/5158262155/jobs/9291720333?pr=6
and it looks like 3.6 was removed in this PR:
https://github.com/cloudchacho/taskhawk-python/pull/5/files

### CODE REVIEW

**Comment by maroux** [comment]
> Should Pulling deadline exceeded be changed to a more friendly message like Queue had no messages though? Or is there a scenario where a DeadlineExceeded exception occurs that's not due to there being no messages?

Good question. [This test](https://github.com/googleapis/python-pubsub/blob/3ffb93602538fc912bcbe0c24f0f4c5d5311fac0/tests/system.py#L495-L519) seems to indicate that's not true, and something else going on, so we should investigate that. Have you tried upgrading pubsub library version?

**Comment by mjneth** [comment]
> 

Hm I just tried with the latest version (2.17.1) of google-cloud-pubsub and it still outputs that constantly.

**Comment by mjneth** [comment]
> > Should Pulling deadline exceeded be changed to a more friendly message like Queue had no messages though? Or is there a scenario where a DeadlineExceeded exception occurs that's not due to there being no messages?
> 
> Good question. [This test](https://github.com/googleapis/python-pubsub/blob/3ffb93602538fc912bcbe0c24f0f4c5d5311fac0/tests/system.py#L495-L519) seems to indicate that's not true, and something else going on, so we should investigate that. Have you tried upgrading pubsub library version?

Hm I just tried with the latest version (2.17.1) of google-cloud-pubsub and it still outputs that constantly.

**Comment by mjneth** [comment]
> > > Should Pulling deadline exceeded be changed to a more friendly message like Queue had no messages though? Or is there a scenario where a DeadlineExceeded exception occurs that's not due to there being no messages?
> > 
> > 
> > Good question. [This test](https://github.com/googleapis/python-pubsub/blob/3ffb93602538fc912bcbe0c24f0f4c5d5311fac0/tests/system.py#L495-L519) seems to indicate that's not true, and something else going on, so we should investigate that. Have you tried upgrading pubsub library version?
> 
> Hm I just tried with the latest version (2.17.1) of google-cloud-pubsub and it still outputs that constantly.
> 
> Supposedly fixed here, odd: [googleapis/python-pubsub#9](https://github.com/googleapis/python-pubsub/issues/9)

The default 5 second timeout for pulling those might just be too fast for how long it takes when there are no messages. I bumped it to 20 seconds and in early tests that error no longer outputs. I'll test a bit more after this donut meeting to see if that actually takes care of it.

**Comment by mjneth** [comment]
> > > > Should Pulling deadline exceeded be changed to a more friendly message like Queue had no messages though? Or is there a scenario where a DeadlineExceeded exception occurs that's not due to there being no messages?
> > > 
> > > 
> > > Good question. [This test](https://github.com/googleapis/python-pubsub/blob/3ffb93602538fc912bcbe0c24f0f4c5d5311fac0/tests/system.py#L495-L519) seems to indicate that's not true, and something else going on, so we should investigate that. Have you tried upgrading pubsub library version?
> > 
> > 
> > Hm I just tried with the latest version (2.17.1) of google-cloud-pubsub and it still outputs that constantly.
> > Supposedly fixed here, odd: [googleapis/python-pubsub#9](https://github.com/googleapis/python-pubsub/issues/9)
> 
> The default 5 second timeout for pulling those might just be too fast for how long it takes when there are no messages. I bumped it to 20 seconds and in early tests that error no longer outputs. I'll test a bit more after this donut meeting to see if that actually takes care of it.

Yeah raising that stopped the error from happening constantly. I added a new "Pulling messages" log so we know the process is up, ready, and not hung since I was relying on the deadline exceeded error for that before. This is ready for you to review again.

**Review by maroux — APPROVED** [review]

**Pull request merged**
